server:
  port: :10001
  name: tecture

log:
  encoding: json
  level: info
  devMode: false

postgres:
  Host: localhost
  Port: 5432
  User: postgres
  Password: postgres
  Dbname: tecture
  Sslmode: require
  PgDriver: pgx
  CreateDb: false

jaeger:
  Host: localhost:6831
  LogSpans: false

redis:
  Host: "localhost:6379"
  Password:
  DefaultDB: 0
  MinIdleConn: 200
  PoolSize: 12000
  PoolTimeout: 240
  DB: 0